import { Dimensions, StyleSheet } from 'react-native';
import { SCREEN_W, THUMB_SIZE } from './types';

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 13,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#DBDBDB',
  },
  headerBack: {
    color: '#262626',
    fontSize: 16,
  },
  headerTitle: {
    color: '#262626',
    fontSize: 16,
    fontWeight: '600',
  },
  headerShare: {
    color: '#0095F6',
    fontSize: 16,
    fontWeight: '600',
  },
  photosStrip: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#DBDBDB',
    paddingVertical: 12,
  },
  photosRow: {
    paddingHorizontal: 14,
    gap: 6,
  },
  photoThumb: {
    width: THUMB_SIZE,
    height: THUMB_SIZE,
    borderRadius: 6,
    backgroundColor: '#EEE',
  },
  photoCount: {
    paddingHorizontal: 14,
    paddingTop: 8,
    fontSize: 12,
    color: '#8E8E8E',
  },
  moodSection: {
    backgroundColor: '#FFFFFF',
    marginTop: 12,
    paddingTop: 14,
    paddingBottom: 4,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: '#DBDBDB',
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8E8E8E',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  moodRow: {
    paddingHorizontal: 14,
    gap: 8,
    paddingBottom: 14,
  },
  moodChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#DBDBDB',
    backgroundColor: '#FAFAFA',
  },
  moodIcon: {
    fontSize: 14,
  },
  moodLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: '#262626',
  },
  moodLabelActive: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  editorSection: {
    backgroundColor: '#FFFFFF',
    marginTop: 12,
    paddingTop: 14,
    paddingBottom: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: '#DBDBDB',
  },
  editorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingRight: 16,
    marginBottom: 10,
  },
  charCount: {
    fontSize: 11,
    color: '#C7C7CC',
  },
  captionEditor: {
    marginHorizontal: 16,
    fontSize: 15,
    color: '#262626',
    lineHeight: 22,
    minHeight: 100,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#DBDBDB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FAFAFA',
  },
  hashtagsSection: {
    backgroundColor: '#FFFFFF',
    marginTop: 12,
    paddingTop: 14,
    paddingBottom: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: '#DBDBDB',
  },
  hashtagsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingRight: 16,
    marginBottom: 10,
  },
  toggleBtn: {
    padding: 4,
  },
  toggleTrack: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#E5E5EA',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  toggleTrackOn: {
    backgroundColor: '#34C759',
  },
  toggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  toggleThumbOn: {
    transform: [{ translateX: 20 }],
  },
  locationInput: {
    marginTop: 8,
    marginHorizontal: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#DBDBDB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#1C1C1E',
    backgroundColor: '#F9F9F9',
  },
  creditRow: {
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: '#DBDBDB',
    backgroundColor: '#FFFFFF',
  },
  creditText: {
    fontSize: 13,
    color: '#8E8E8E',
  },
  hashtagsText: {
    paddingHorizontal: 16,
    fontSize: 14,
    color: '#0095F6',
    lineHeight: 22,
  },
  previewSection: {
    marginTop: 12,
    paddingTop: 14,
    backgroundColor: '#FFFFFF',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: '#DBDBDB',
  },
  previewCard: {
    backgroundColor: '#FFFFFF',
  },
  previewPostHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  previewAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#0095F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewAvatarText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: '700',
  },
  previewUsername: {
    fontSize: 13,
    fontWeight: '600',
    color: '#262626',
  },
  previewImageSlot: {
    width: SCREEN_W,
    height: SCREEN_W,
    backgroundColor: '#000',
    overflow: 'hidden',
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  carouselBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  carouselBadgeText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '600',
  },
  previewCaption: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 16,
  },
  previewCaptionText: {
    fontSize: 14,
    color: '#262626',
    lineHeight: 20,
  },
});

export default styles;
